# .github/workflows/main.yml

name: 🔄 CI – Vault Template Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Install dependencies
        env:
          OFFLINE: 1
        run: ./setup.sh
      
